config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'tests/solution/:id' => 'tests#show_solution', as: :show_solution
  resources :tests

  get 'tasks/by_tags' #=> 'tasks#by_tags'
  resources :tasks

  resources :students, :except => :show

  get 'main/index'
  root 'main#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :question, presence: true
  validates :tags_line, presence: true

  belongs_to :author, :class_name => 'User'

  has_many :task_user_tags, dependent: :destroy
  has_many :user_tags, through: :task_user_tags

  has_many :student_tasks, dependent: :destroy
  has_many :students, through: :student_tasks
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  respond_to :html
  respond_to :json, only: :by_tags

  def index
    @tasks_user_tags = TaskUserTag.
        includes(:task, :user_tag).
        where('tasks.author_id = ?', current_user.id).
        order('user_tags.tag', 'tasks.created_at')
    if @tasks_user_tags.empty?
      redirect_to new_task_path
    else
      respond_with(@tasks_user_tags)
    end
  end

  def show
    respond_with(@task)
  end

  def new
    @task = Task.new
    respond_with(@task)
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.save
    update_tags
    redirect_to tasks_path
  end

  def update
    @task.update(task_params)
    update_tags
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
    respond_with(@task)
  end

  def by_tags
    tag_ids = params[:tags]
    unique_for = params[:unique_for]

    if unique_for and digits?(unique_for)
      student_id = unique_for.to_i
    else
      student_id = nil
    end

    task_limit = 20

    if tag_ids and student_id
      # suuuuuper slow :(
      ids = tag_ids.split(',').map(&:strip).map(&:to_i)
      puts 'IDS', ids.inspect
      tasks = Task.joins(:user_tags).where('user_tags.id' => ids, author_id: current_user.id).
          limit(task_limit).distinct
      ignored_student_tasks = StudentTask.where({student_id: student_id}).where({task_id: tasks})
      ignored_task_ids = Set.new ignored_student_tasks.map &:task_id
      @tasks = tasks.select {|task| not ignored_task_ids.include? task.id}
    elsif tag_ids
      ids = tag_ids.split(',').map(&:strip).map(&:to_i)
      @tasks = Task.joins(:user_tags).where('user_tags.id' => ids, author_id: current_user.id).
          limit(task_limit).distinct
    else
      @tasks = []
    end

    respond_with(@tasks)
  end

  private
    def set_task
      @task = Task.where(id: params[:id], author_id: current_user.id).first!
    end

    def task_params
      default_params = {author_id: current_user.id}
      params.require(:task).permit(:question, :answer, :extra_text, :tags_line).merge default_params
    end

    def update_tags
      line = @task.tags_line
      tag_names = get_tag_names(line)
      tags = @task.user_tags
      mapping_tags = {}
      tags.each {|tag| mapping_tags[tag.tag] = tag }
      used_tag_names = Set.new(tags.map &:tag)
      unused_tag_names = used_tag_names - tag_names
      unused_tag_names.each do |tag_name|
        mapping_tags[tag_name].destroy
      end
      new_tag_names = tag_names - used_tag_names
      new_tag_names.each do |tag_name|
        @task.user_tags << UserTag.where(user_id: current_user.id, tag: tag_name).first_or_create
      end
    end

    def get_tag_names(tags_line)
      Set.new (tags_line.split(',').map &:strip).select {|v| v.size > 0}
    end

    def digits?(text)
      normalized = text.strip
      normalized.size == normalized.to_i.to_s.size
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_field :answer %>
  </div>
  <div class="field">
    <%= f.label :tags_line %><br>
    <%= f.text_field :tags_line %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="header">
    <nav>
      <ul class="nav nav-pills pull-right">
        <li role="presentation"><a href="<%= tests_path %>"><span class="glyphicon glyphicon-book" aria-hidden="true"></span> Testy</a></li>
        <li role="presentation" class="active"><a href="<%= tasks_path %>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Zdania</a></li>
        <li role="presentation"><a href="<%= students_path %>"><span class="glyphicon glyphicon-user"></span> Uczniowie</a></li>
        <li role="presentation"><a href="<%= destroy_user_session_path %>" data-method="delete"><span class="glyphicon glyphicon-off"></span> Wyloguj się</a></li>
      </ul>
    </nav>
    <h3 class="text-muted">Test Factory</h3>
  </div>

  <div class="row">
    <div class="col-md-12">
      <%= form_for(@task, html: {role: "form"}) do |f| %>
          <% if @task.errors.any? %>
              <div class="alert alert-danger" role="alert">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <span class="sr-only">Error:</span><%= @task.errors.first[0] %> <%= @task.errors.first[1] %>
              </div>
          <% end %>

          <div class="form-group">
            <%= f.label 'Zdanie' %><br>
            <%= f.text_field :question, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label 'Tłumaczenie' %><br>
            <%= f.text_field :answer, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label 'Mój tekst' %><br>
            <%= f.text_field :extra_text, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label 'Tagi' %><br>
            <%= f.text_field :tags_line, class: 'form-control' %>
          </div>
          <div class="actions">
            <%= f.submit 'Zapisz zdanie', class:  'btn btn-lg btn-primary btn-block' %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="header">
    <nav>
      <ul class="nav nav-pills pull-right">
        <li role="presentation"><a href="<%= tests_path %>"><span class="glyphicon glyphicon-book" aria-hidden="true"></span> Testy</a></li>
        <li role="presentation" class="active"><a href="<%= tasks_path %>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Zdania</a></li>
        <li role="presentation"><a href="<%= students_path %>"><span class="glyphicon glyphicon-user"></span> Uczniowie</a></li>
        <li role="presentation"><a href="<%= destroy_user_session_path %>" data-method="delete"><span class="glyphicon glyphicon-off"></span> Wyloguj się</a></li>
      </ul>
    </nav>
    <h3 class="text-muted">Test Factory</h3>
  </div>
    <% @tasks_user_tags.group_by {|tut| tut.user_tag.tag}.each do |tag, tasks_user_tags| %>
          <table class="table table-striped">
            <thead>
            <tr>
              <th><span class="label label-info"><%= tag %></span></th>
              <th colspan="3"></th>
            </tr>
            </thead>

            <tbody>
            <% tasks_user_tags.each do |task_user_tag|%>
                <tr>
                  <td><strong><%= task_user_tag.task.question %></strong></td>
                  <td><%= link_to raw('<span class="glyphicon glyphicon-eye-open"></span> Podgląd'), task_user_tag.task %></td>
                  <td><%= link_to raw('<span class="glyphicon glyphicon-wrench"></span> Edytuj'), edit_task_path(task_user_tag.task) %></td>
                  <td><%= link_to 'Usuń', task_user_tag.task, method: :delete, class: 'label label-danger', data: { confirm: 'Jesteś pewien?' } %></td>
                </tr>
            <% end %>
            </tbody>
          </table>
    <% end %>
<br>

<%= link_to 'Dodaj zdanie', new_task_path, class: 'btn btn-primary' %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="header">
    <nav>
      <ul class="nav nav-pills pull-right">
        <li role="presentation"><a href="<%= tests_path %>"><span class="glyphicon glyphicon-book" aria-hidden="true"></span> Testy</a></li>
        <li role="presentation" class="active"><a href="<%= tasks_path %>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Zdania</a></li>
        <li role="presentation"><a href="<%= students_path %>"><span class="glyphicon glyphicon-user"></span> Uczniowie</a></li>
        <li role="presentation"><a href="<%= destroy_user_session_path %>" data-method="delete"><span class="glyphicon glyphicon-off"></span> Wyloguj się</a></li>
      </ul>
    </nav>
    <h3 class="text-muted">Test Factory</h3>
  </div>

  <div class="row">
    <div class="col-md-12">

  <%= form_for(@task, html: {role: "form"}) do |f| %>
    <% if @task.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

          <ul>
            <% @task.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label 'Zdanie' %><br>
      <%= f.text_field :question, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label 'Tłumaczenie' %><br>
      <%= f.text_field :answer, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label 'Mój tekst' %><br>
        <%= f.text_field :extra_text, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label 'Tagi' %><br>
      <%= f.text_field :tags_line, class: 'form-control' %>
    </div>
    <div class="actions">
      <%= f.submit 'Dodaj zdanie', class:  'btn btn-lg btn-primary btn-block' %>
    </div>
<% end %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="header">
    <nav>
      <ul class="nav nav-pills pull-right">
        <li role="presentation"><a href="<%= tests_path %>"><span class="glyphicon glyphicon-book" aria-hidden="true"></span> Testy</a></li>
        <li role="presentation" class="active"><a href="<%= tasks_path %>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Zdania</a></li>
        <li role="presentation"><a href="<%= students_path %>"><span class="glyphicon glyphicon-user"></span> Uczniowie</a></li>
        <li role="presentation"><a href="<%= destroy_user_session_path %>" data-method="delete"><span class="glyphicon glyphicon-off"></span> Wyloguj się</a></li>
      </ul>
    </nav>
    <h3 class="text-muted">Test Factory</h3>
  </div>

  <div class="row">
    <div class="panel panel-default">
    <form class="form-horizontal" role="form">

      <div class="form-group">
        <label class="col-sm-2 control-label">Zadanie</label>
        <div class="col-sm-10">
          <p class="form-control-static"><%= @task.question %></p>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">Tłumaczenie</label>
        <div class="col-sm-10">
          <p class="form-control-static"><%= @task.answer %></p>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">Mój tekst</label>
        <div class="col-sm-10">
          <p class="form-control-static"><%= @task.extra_text %></p>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">Tagi</label>
        <div class="col-sm-10">
          <p class="form-control-static">
          <% @task.user_tags.each do |user_tag| %>
              <span class="label label-info"><%= user_tag.tag %></span>
          <% end %>
          </p>
        </div>
      </div>
    </form>
  </div>
</div>
  <p><%= link_to raw('<span class="glyphicon glyphicon-wrench"></span> Edytuj'), edit_task_path(@task), class: 'btn btn-primary' %></p>
</div>