config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'tests/solution/:id' => 'tests#show_solution', as: :show_solution
  resources :tests

  get 'tasks/by_tags' #=> 'tasks#by_tags'
  resources :tasks

  resources :students, :except => :show

  get 'main/index'
  root 'main#index'

end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :teacher, :class_name => 'User'
  validates :name, presence: true
  has_many :student_tasks, dependent: :destroy
  has_many :tasks, through: :student_tasks
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_student, only: [:edit, :update, :destroy]

  respond_to :html

  def index
    @students = Student.where(teacher_id: current_user.id).order(created_at: :desc)
    respond_with(@students)
  end

  def new
    @student = Student.new
    respond_with(@student)
  end

  def edit
  end

  def create
    @student = Student.new(student_params)
    @student.save
    redirect_to students_path
  end

  def update
    @student.update(student_params)
    redirect_to students_path
  end

  def destroy
    @student.destroy
    respond_with(@student)
  end

  private
    def set_student
      @student = Student.where(id: params[:id], teacher_id: current_user.id).first!
    end

    def student_params
      default_params = {teacher_id: current_user.id}
      params.require(:student).permit(:name).merge default_params
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/edit.html.erb
<div class="container">
  <div class="header">
    <nav>
      <ul class="nav nav-pills pull-right">
        <li role="presentation"><a href="<%= tests_path %>"><span class="glyphicon glyphicon-book" aria-hidden="true"></span> Testy</a></li>
        <li role="presentation"><a href="<%= tasks_path %>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Zdania</a></li>
        <li role="presentation" class="active"><a href="<%= students_path %>"><span class="glyphicon glyphicon-user"></span> Uczniowie</a></li>
        <li role="presentation"><a href="<%= destroy_user_session_path %>" data-method="delete"><span class="glyphicon glyphicon-off"></span> Wyloguj się</a></li>
      </ul>
    </nav>
    <h3 class="text-muted">Test Factory</h3>
  </div>

  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <%= form_for(@student, html: {role: "form"}) do |f| %>
          <% if @student.errors.any? %>
              <div class="alert alert-danger" role="alert">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <span class="sr-only">Error:</span><%= @student.errors.first[0] %> <%= @student.errors.first[1] %>
              </div>
          <% end %>
          <div class="form-group">
            <%= f.label 'Nazwa ucznia' %><br>
            <%= f.text_field :name, autofocus: true, class: 'form-control'%>
          </div>
          <div class="actions">
            <%= f.submit 'Zapisz zmiany', class:  'btn btn-lg btn-primary btn-block' %>
          </div>
      <% end %>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>

app/views/students/index.html.erb
<div class="container">
  <div class="header">
    <nav>
      <ul class="nav nav-pills pull-right">
        <li role="presentation"><a href="<%= tests_path %>"><span class="glyphicon glyphicon-book" aria-hidden="true"></span> Testy</a></li>
        <li role="presentation"><a href="<%= tasks_path %>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Zdania</a></li>
        <li role="presentation" class="active"><a href="<%= students_path %>"><span class="glyphicon glyphicon-user"></span> Uczniowie</a></li>
        <li role="presentation"><a href="<%= destroy_user_session_path %>" data-method="delete"><span class="glyphicon glyphicon-off"></span> Wyloguj się</a></li>
      </ul>
    </nav>
    <h3 class="text-muted">Test Factory</h3>
  </div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nazwa ucznia</th>
      <th>Data utworzenia</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><strong><%= student.name %></strong></td>
        <td><%= student.created_at.to_date %></td>
        <td><%= link_to raw('<span class="glyphicon glyphicon-wrench"></span> Edytuj'), edit_student_path(student) %></td>
        <td><%= link_to 'Usuń', student, method: :delete, class: 'label label-danger', data: { confirm: 'Jesteś pewien?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Dodaj ucznia', new_student_path, class: 'btn btn-primary' %>

</div>

app/views/students/new.html.erb
<div class="container">
  <div class="header">
    <nav>
      <ul class="nav nav-pills pull-right">
        <li role="presentation"><a href="<%= tests_path %>"><span class="glyphicon glyphicon-book" aria-hidden="true"></span> Testy</a></li>
        <li role="presentation"><a href="<%= tasks_path %>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Zdania</a></li>
        <li role="presentation" class="active"><a href="<%= students_path %>"><span class="glyphicon glyphicon-user"></span> Uczniowie</a></li>
        <li role="presentation"><a href="<%= destroy_user_session_path %>" data-method="delete"><span class="glyphicon glyphicon-off"></span> Wyloguj się</a></li>
      </ul>
    </nav>
    <h3 class="text-muted">Test Factory</h3>
  </div>

  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <%= form_for(@student, html: {role: "form"}) do |f| %>
          <% if @student.errors.any? %>
              <div class="alert alert-danger" role="alert">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <span class="sr-only">Error:</span><%= @student.errors.first[0] %> <%= @student.errors.first[1] %>
              </div>
          <% end %>
          <div class="form-group">
            <%= f.label 'Nazwa ucznia' %><br>
            <%= f.text_field :name, autofocus: true, class: 'form-control'%>
          </div>
          <div class="actions">
            <%= f.submit 'Dodaj ucznia', class:  'btn btn-lg btn-primary btn-block' %>
          </div>
      <% end %>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>